Repository octopusden/octopus-dms-service, pull requests merged in 2023-11, with the labels that each got.

#2 add exec permission for gradle
  gradlew
Labels: build

#1 Rename wlignore.json to .wlignore.json
  .wlignore.json
Labels: bug

#4 Use ext properties. Reimplement skip signing.
  .run/FT.run.xml
  .run/UT.run.xml
  build.gradle.kts
  client/client/build.gradle.kts
  client/gradle-dms-client/build.gradle.kts
  client/gradle-dms-plugin/build.gradle.kts
  client/maven-dms-plugin/build.gradle.kts
  common/build.gradle.kts
  ft/build.gradle.kts
  metarunners/build.gradle.kts
  server/build.gradle.kts
Labels: build

#5 Fix signing in gradle-dms-plugin subproject
  client/gradle-dms-plugin/build.gradle.kts
Labels: build

#6 Dump all validation errors in validation log
  client/maven-dms-plugin/src/main/java/org/octopusden/octopus/dms/client/service/DMSServiceImpl.java
  ft/src/ft/kotlin/org/octopusden/octopus/dms/DmsServiceApplicationFunctionalTest.kt
  ft/src/ft/resources/test-gradle-dms-plugin/build.gradle.kts
  ft/src/ft/resources/test-gradle-dms-plugin/settings.gradle.kts
Labels: enhancement

#7 Add gradle plugin description
  client/gradle-dms-plugin/build.gradle.kts
Labels: build

#8 Sync writing to file in maven-dms-plugin.
  client/maven-dms-plugin/src/main/java/org/octopusden/octopus/dms/client/service/DMSServiceImpl.java
  client/maven-dms-plugin/src/main/java/org/octopusden/octopus/dms/client/util/Utils.java
Labels: enhancement

#9 Fix write-to-file.
  client/maven-dms-plugin/src/main/java/org/octopusden/octopus/dms/client/service/DMSServiceImpl.java
  client/maven-dms-plugin/src/main/java/org/octopusden/octopus/dms/client/util/Utils.java
Labels: bug
