Repository octopusden/octopus-dms-service, pull requests merged in 2024-06, with the labels that each got.

#19 Added a check for mandatory parameter completion.
  client/gradle-dms-client/src/main/java/org/octopusden/octopus/dms/client/ArtifactDownloader.java
Labels: enhancement

#20 Add DMS UI
  .gitignore
  .run/DmsService (bootRun, frontend live reload).run.xml
  .run/DmsService (dev).run.xml
  .run/Frontend (dev).run.xml
  README.md
  ft/src/ft/docker/docker-compose.yaml
  server/.babelrc
  server/.eslintrc.json
  server/build.gradle.kts
  server/dev/api-gateway.yaml
  server/dev/application-dev.yml
  server/dev/docker-compose.yml
  server/package-lock.json
  server/package.json
  server/postcss.config.js
  server/src/frontend/components/AdminPane/index.js
  server/src/frontend/components/AdminPane/presenter.jsx
  server/src/frontend/components/AdminPane/style.css
  server/src/frontend/components/App.js
  server/src/frontend/components/ArtifactList/index.js
  server/src/frontend/components/ArtifactList/presenter.jsx
  server/src/frontend/components/ArtifactList/style.css
  server/src/frontend/components/Components/index.js
  server/src/frontend/components/Components/presenter.jsx
  server/src/frontend/components/Components/style.css
  server/src/frontend/components/ComponentsTree/Search/Search.css
  server/src/frontend/components/ComponentsTree/Search/Search.jsx
  server/src/frontend/components/ComponentsTree/index.js
  server/src/frontend/components/ComponentsTree/presenter.jsx
  server/src/frontend/components/ComponentsTree/style.css
  server/src/frontend/components/Footer/index.js
  server/src/frontend/components/Footer/presenter.jsx
  server/src/frontend/components/Footer/style.css
  server/src/frontend/components/Header/index.js
  server/src/frontend/components/Header/presenter.jsx
  server/src/frontend/components/Header/style.css
  server/src/frontend/components/Meta/index.js
  server/src/frontend/components/Meta/presenter.jsx
  server/src/frontend/components/Meta/style.css
  server/src/frontend/components/Preview/index.js
  server/src/frontend/components/Preview/presenter.jsx
  server/src/frontend/components/Preview/style.css
  server/src/frontend/components/common.js
  server/src/frontend/components/duck/actions.js
  server/src/frontend/components/duck/index.js
  server/src/frontend/components/duck/operations.js
  server/src/frontend/components/duck/reducers.js
  server/src/frontend/components/duck/types.js
  server/src/frontend/index.css
  server/src/frontend/index.html
  server/src/frontend/index.js
  server/src/frontend/reducers.js
  server/src/frontend/utils/fakeLoaders.js
  server/src/frontend/utils/history.js
  server/src/main/kotlin/org/octopusden/octopus/dms/configuration/WebConfig.kt
  server/src/main/kotlin/org/octopusden/octopus/dms/controller/AuthController.kt
  server/webpack.common.js
  server/webpack.dev.js
  server/webpack.prod.js
  server/yarn.lock
Labels: enhancement

#21 fix validation
  .wlignore.json
Labels: build

#23 Fix artifact downloading
  server/src/frontend/components/ArtifactList/presenter.jsx
  server/src/frontend/components/duck/operations.js
Labels: bug
